### PR TITLE
- Fixed broken link to perlapi keyword plugin.

### PR DESCRIPTION
**Pull request by Manwar**
Hi, please review the above change.

Many Thanks.
Best Regards,
Mohammad S Anwar

### CODE REVIEW

**Comment by mauke** [comment]
`L<foo>` is how you're supposed to link to perldoc pages: http://perldoc.perl.org/perlpod.html#Formatting-Codes

`L<perlapi>` seems to be broken on metacpan but I think that's a metacpan bug.

**Comment by Manwar** [comment]
Hi,

You are right about showing links on pod document.
However the code for "perlapi" is no longer available on metacpan and hence the link is broken. Therefore I suggest to link it to other place where the code is available.

Best Regards,
Mohammad S Anwar

**Comment by mauke** [comment]
Now reported as https://github.com/CPAN-API/metacpan-web/issues/1628.

How do I generate special POD for metacpan to make it link elsewhere?

**Comment by Manwar** [comment]
Please refer to my PR, I created link to outside of MetaCPAN.

**Comment by mauke** [comment]
This would break other POD viewers with (non-http) hyperlink support.

**Pull request closed without merging**
